server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:  postgres
    password:  postgres
    driver-class-name:  org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.github.brandonbai.smartmonitor.pojo