server:
  port: 8082

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
  datasource:
    url: jdbc:mysql://localhost:3306/smartmonitor
    username:  root
    password:  root
    driver-class-name:  com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 192.168.85.155
    port: 6379
    password:
    pool:
      max-idle: 8
      max-wait: -1
    timeout: 0

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.github.brandonbai.smartmonitor.pojo

mqtt:
  url: tcp://192.168.85.155gi:1883
  username: lilei
  password: 123456

logging:
  level: info
